### ISSUE TITLE
Components from multiple version numbers get combined

### ISSUE THREAD

**Issue by DomoSokrat** [kaushalmodi/version#10]
If the output of a cli app contains multiple version numbers, then components of those get combined.

One example is pypy:

```
$ version pypy
pypy version: 8.3.13
  Python 2.7.13 (4a68d8d3d2fc1faec2e83bcb4d28559099092574, Nov 10 2019, 19:37:56)
  [PyPy 7.2.0 with GCC 8.3.0]
```

I don't expect version to pick the right version number for this case, but it should not combine '2.7.13' and '8.3.0' to '8.3.13'.

**Comment by kaushalmodi** [comment]
Thanks for trying this out, and more importantly, reporting it. This will be a nice test case :)

**Comment by kaushalmodi** [comment]
@DomoSokrat This is now fixed. It now returns 7.2.0. Please try out the latest from master or download the fixed version from https://github.com/kaushalmodi/version/releases/download/v0.3.0/version-v0.3.0.Linux_64bit_musl.tar.xz .

Let me know if this is fixed for more cases for you.
